### PR TITLE
Updates to work with Mopidy 1.0

### PR DESCRIPTION
**Pull request by jodal**
Without this change, playback will no longer work with Mopidy 1.0.

In other words, it's about time to update your changelog with all the changes from the last year and get ready to do a release as soon as Mopidy 1.0 is out :-)

### CODE REVIEW

**Comment by jodal** [comment]
I should add: The motivation for this breaking change is to be able to support gapless playback in Mopidy 1.1.

**Comment by jodal** [comment]
The remaining broken tests are due to playlist API changes. I'll send you another PR when the last part of that lands in Mopidy's develop branch later today.

**Comment by jodal** [comment]
With those commits, Mopidy-GMusic should be up to date with Mopidy 1.0 and all tests should pass.

**Comment by jodal** [comment]
I added another commit to update `library.search()` to accept an `exact` kwarg and made `find_exact()` an internal implementation detail as it is no longer part of the backend API in Mopidy 1.0.

**Comment by hechtus** [comment]
Thanks a lot! Please let me know, when you think everything is fine.

**Comment by jodal** [comment]
Mopidy 1.0 was released yesterday. These changes should be all updates that
are required. In other words, if the changes work for you, it's time to
release :)

**Comment by morgoth** [comment]
@hechtus are there any doubts on this PR? Would love to try Mopidy 1.0 with this plugin

**Comment by hechtus** [comment]
@morgoth Just merged. Could you please try it out?

**Comment by morgoth** [comment]
Sure, can you give me a hint how to install it properly from master branch?

**Comment by jodal** [comment]
To install a snapshot of the develop branch, where this was merged, run:

```
pip install https://github.com/hechtus/mopidy-gmusic/archive/develop.zip
```

**Comment by morgoth** [comment]
Looks like all is working fine.

**Pull request merged**
